config/routes.rb
Isgetir::Application.routes.draw do

  root :to => 'jobs#index'

  match ':locale/jobs/search' => 'jobs#search', :as => "search"
  match 'jobs/search_autocomplete' => 'jobs#search_autocomplete'
  match ':locale/search_by_cat_id' => 'jobs#search_by_cat_id', :as => 'search_by_cat_id' # according to
  match ":locale/jobs/user_jobs" => "jobs#user_jobs", :as => "user_jobs"

  match 'comment_destroy_path' => "comments#destroy"

  scope "/:locale" do
    resources :jobs do

      member do
        post :notify_friend
      end
      collection do
        get :search_autocomplete
        get :search
        get :ajaxing
        get :search_by_cat_id
      end
      resources :comments
    end
  end

  match 'users/admin_update_user_interface' => 'users#admin_update_user_interface', :as => 'admin_update_user_interface'

=begin

  match 'users/admin_updated_user' => 'users#admin_updated_user', :as => 'admin_updated_user'

  match 'users/admin_manage' => 'users#admin_manage', :as => 'admin_manage'

  match 'users/admin' => 'users#admin', :as => 'user_admin'

  match 'users/admin_edit_user' => "users#admin_edit_user", :as => 'admin_edit_user'

  match 'users/admin_change_password' => 'users#admin_change_password', :as => 'admin_change_password'

  resources :users
=end

  match ":locale/admin_manage/:manage" => "users#admin_manage", :as => "admin_manage_users"

  scope "/:locale" do
    resources :users do
      collection do
        put :admin_updated_user
        get :admin_update_user_interface
        get :admin
        get :admin_edit_user
        put :admin_change_password
      end
    end
  end

  match 'users/destroy' => "users#destroy"

  resource :session, :only => [:new, :create, :destroy] # , :only => [:new, :create, :destroy] added after reading rails by example

  resources :password_resets

  match ":locale/login_for_user_jobs/:login_for_user_jobs" => "sessions#new", :as =>"login_for_user_jobs"

  match '/login' => "sessions#new", :as => "login" # according to
  match '/logout' => "sessions#destroy", :as => "logout" # according to

end

app/views/notifier/comment_added.html.erb
<html>
<body>
<p>
<%= t('notifier.comment_added.comment_added') %> (<i><%= @job.title %></i>).
<%= t('notifier.comment_added.read_it_at') %>:
  <%= link_to(url_for(locale: locale,
                controller: 'jobs',
                action: 'show',
                id: @job.id,
                host: "www.isgetir.com"),
                url_for(locale: locale,
                controller: 'jobs',
                action: 'show',
                id: @job.id,
                host: "www.isgetir.com"))%>

    <!-- asagidaki job_url methodu routing error veriyor:
        'no route matches action=show controller=jobs...' -->
   <!-- link_to @job.title, job_url(@job, :host => 'www.isgetir.com') -->.
</p>
</body>
</html>

app/views/notifier/email_friend.html.erb
<html>
<body>
<p>
<%= t('notifier.email_friend.one_of_your_friend') %>, <%= @sender_name %>,
<%= t('notifier.email_friend.you_might_like_this') %>.
</p>
<p>
<strong><%= @job.title %></strong>
  <br />
  <%= link_to(url_for(locale: locale,
              controller: 'jobs',
              action: 'show',
              id: @job.id,
              host: "www.isgetir.com"),
              url_for(locale: locale,
              controller: 'jobs',
              action: 'show',
              id: @job.id,
              host: "www.isgetir.com"))%>

  <!-- asagidaki job_url methodu routing error veriyor:
      'no route matches action=show controller=jobs...' -->
  <!-- link_to job_url(@job, :host => 'www.isgetir.com'),
        job_url(@job, :host => 'www.isgetir.com') -->
</p>
</body>
</html>

app/views/notifier/job_added.html.erb
<html>
<body>
<p>
<%= t('notifier.job_added.job_added_with_this_title') %>: <i><%= @job.title %></i>.
<br /><br />
<%= t('notifier.job_added.job_body') %>: "<%= @job.body %>"
<br /><br />
<%= t('notifier.job_added.posted_user_email_address') %>: <%= @job.user.email %>
<br /><br />
<%= t('notifier.job_added.to_read_the_posted_job') %>
  <%= link_to(url_for(locale: locale,
                controller: 'jobs',
                action: 'show',
                id: @job.id,
                host: "www.isgetir.com"),
                url_for(locale: locale,
                controller: 'jobs',
                action: 'show',
                id: @job.id,
                host: "www.isgetir.com"))%>

    <!-- asagidaki job_url methodu routing error veriyor:
        'no route matches action=show controller=jobs...' -->
    <!-- link_to @job.title, job_url(@job, :host => 'www.isgetir.com') -->
</p>
</body>
</html>

app/views/notifier/password_reset.html.erb
<html>
<body>
<p>
<br /><br />
<%= t('notifier.password_reset.to_reset_your_password') %>:
<br /><br />
<%= link_to edit_password_reset_url(@user.password_reset_token),
            edit_password_reset_url(@user.password_reset_token) %>
<br /><br />
<%= t('notifier.password_reset.to_ignore_reset') %>.
<br /><br />
</p>
</body>
</html>

app/views/notifier/user_added.html.erb
<html>
<body>
<p>
<%= t('notifier.user_added.new_user_added') %>:<i><%= @user.email %></i>.
</p>
</body>
</html>