config/routes.rb
Isgetir::Application.routes.draw do

  root :to => 'jobs#index'

  match ':locale/jobs/search' => 'jobs#search', :as => "search"
  match 'jobs/search_autocomplete' => 'jobs#search_autocomplete'
  match ':locale/search_by_cat_id' => 'jobs#search_by_cat_id', :as => 'search_by_cat_id' # according to
  match ":locale/jobs/user_jobs" => "jobs#user_jobs", :as => "user_jobs"

  match 'comment_destroy_path' => "comments#destroy"

  scope "/:locale" do
    resources :jobs do

      member do
        post :notify_friend
      end
      collection do
        get :search_autocomplete
        get :search
        get :ajaxing
        get :search_by_cat_id
      end
      resources :comments
    end
  end

  match 'users/admin_update_user_interface' => 'users#admin_update_user_interface', :as => 'admin_update_user_interface'

=begin

  match 'users/admin_updated_user' => 'users#admin_updated_user', :as => 'admin_updated_user'

  match 'users/admin_manage' => 'users#admin_manage', :as => 'admin_manage'

  match 'users/admin' => 'users#admin', :as => 'user_admin'

  match 'users/admin_edit_user' => "users#admin_edit_user", :as => 'admin_edit_user'

  match 'users/admin_change_password' => 'users#admin_change_password', :as => 'admin_change_password'

  resources :users
=end

  match ":locale/admin_manage/:manage" => "users#admin_manage", :as => "admin_manage_users"

  scope "/:locale" do
    resources :users do
      collection do
        put :admin_updated_user
        get :admin_update_user_interface
        get :admin
        get :admin_edit_user
        put :admin_change_password
      end
    end
  end

  match 'users/destroy' => "users#destroy"

  resource :session, :only => [:new, :create, :destroy] # , :only => [:new, :create, :destroy] added after reading rails by example

  resources :password_resets

  match ":locale/login_for_user_jobs/:login_for_user_jobs" => "sessions#new", :as =>"login_for_user_jobs"

  match '/login' => "sessions#new", :as => "login" # according to
  match '/logout' => "sessions#destroy", :as => "logout" # according to

end

app/models/job.rb
class Job < ActiveRecord::Base

  # attr_accessible'da :references_attributes olmadan references table'a veri eklemiyor
  attr_accessible :title, :body, :location, :category_id, :references_attributes

  #default_scope :order => 'created_at DESC'

  validates :title, :presence => true
  validates :body, :presence => true
  validates :body, :length => { :maximum => 300 }
  validates :user_id, :presence => true
  #validates :category_id, :presence => true

  belongs_to :user
  #has_many :job_categories
  belongs_to :category
  has_many :comments
  has_many :references, :dependent => :destroy
  accepts_nested_attributes_for :references, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true

  simple_search :title, :body, :location

  scope :created, where("jobs.created_at IS NOT NULL")
  scope :recent, lambda { created.where("jobs.created_at > ?", 1.week.ago.to_date)}
  scope :where_title, lambda { |term| where("jobs.title LIKE ?", "%#{term}%") }
  scope :cat_by_name, joins(:category).order('categories.name')
  scope :cat_by_isim, joins(:category).order('categories.isim')

  # Asagidaki category_by_name ve category_by_isim methodlari yerine :cat_by_name ve :cat_by_id scopelarini kullandim
  # Asagidaki iki method "undefined method 'sub' for ActiveRecord::Relation" hatasini veriyor
  # Hatanin sebebini anladim sanirim: method adlari onune self koymayi unutmusum
  #def self.category_by_name
  #  Job.joins(:category).order('categories.name')
  #end
  #
  #def self.category_by_isim
  #  Job.joins(:category).order('categories.isim')
  #end


  def self.search_by_category(cat_id)
    #paginate :per_page => 1, :page => page, :conditions => ['category_id = ?', "#{cat_id}"]
    return Job.where("category_id = ?", cat_id)
  end

  def long_title
    "#{title} - #{published_at}"
  end

  def owned_by?(owner)
    return false unless owner.is_a? User
    # user is defined in sessions_controller
    user == owner
  end

end

app/controllers/jobs_controller.rb
# encoding: utf-8


require 'will_paginate/array'

# https://github.com/mislav/will_paginate/issues/163
# The Array#paginate method still exists, too, but is not loaded by default.
# If you need to paginate static arrays, first require it in your code:
# require 'will_paginate/array'

# for the following error that happened to me:
# NoMethodError (undefined method `paginate' for []:Array):
# app/controllers/jobs_controller.rb:57:in `search_by_category'

class JobsController < ApplicationController
  before_filter :authenticate,
                :except => [:index, :show, :notify_friend, :search,
                            :search_autocomplete, :search_by_cat_id]

  #respond_to :html, :js

  helper_method :sort_column, :sort_direction


  def search_by_cat_id
      if params[:page].to_s == ""
        #puts "**********             #{params}       ***************"
        params[:page]=1
      end

    if !params[:job].nil?
      if params[:job][:category_id].nil?
        #puts "************************************************0*************************************************"
        sorting
      end


      if params[:job][:category_id].to_s==""
        #puts "************************************************1*************************************************"
        sorting
      end

      if params[:job][:category_id].to_i > 0
        @jobs = Job.search_by_category(params[:job][:category_id]).order(sort_column + " " + sort_direction)
        #puts "**********             #{params}       *********************************** #{@jobs.inspect}"
        #puts "*************************Jobs is not nil********************************              ***************"
        @jobs_paged = @jobs.paginate(:per_page => 20, :page => params[:page])
      end
    end

    if params[:job].nil? && params[:category_id].to_s==""
      #puts "************************************************2*************************************************"
      sorting
    end

    if params[:category_id].to_i > 0
        @jobs = Job.search_by_category(params[:category_id]).order(sort_column + " " + sort_direction)
        #puts "**********             #{params}       *********************************** #{@jobs.inspect}"
        #puts "*************************Jobs is nil********************************              ***************"
        @jobs_paged = @jobs.paginate(:per_page => 20, :page => params[:page])
    end

        @jobs = @jobs.paginate(:per_page => 20, :page => params[:page])
      #puts "**********             #{params}       *********************************** #{@jobs_paged.nil?}"

      if !@jobs_paged.nil? && @jobs_paged.empty?
        #puts "**********             #{params}       ***************Jobs Empty ******************************** #{@jobs.inspect}"
        @jobs = @jobs.paginate(:per_page => 20, :page => 1)

      end

    #if params[:locale]=="tr"
    #  I18n.locale = :tr
    #end
    #if params[:locale]=="en"
    #  I18n.locale = :en
    #end

    #end

    render 'index'

    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.js  # burda ajaxing.js.erb invoke edilsin istiyorum
    #  format.json { render json: @jobs }
    #end
  end


  def search

    if params[:page].to_s == ""
      #puts "**********             #{params}       ***************"
      params[:page]=1
    end

    if (params[:category_id]=="0")
      puts "(((((((((((((((((((((((((((((#{params[:keyword].blank?})))))))))))))))))))))))))))))))))))))))"
      #@jobs = Job.limit(0).paginate(:per_page => 1, :page => params[:page])
      @jobs = Job.order(sort_column + " " + sort_direction)
          .paginate(:per_page => 20, :page => params[:page])
      return
    end

    if (params[:keyword].blank?)
      puts "(((((((((((((((((((((((((((((#{params[:keyword].blank?})))))))))))))))))))))))))))))))))))))))"
      #@jobs = Job.limit(0).paginate(:per_page => 1, :page => params[:page])
      @jobs = Job.order(sort_column + " " + sort_direction)
          .paginate(:per_page => 20, :page => params[:page])
      redirect_to :action => :index
      return
    else

      # @jobs = Job.find(params[:keyword]).order(sort_column + " " + sort_direction)  hata veriyor array has not method order
      @jobs = Job.find_by_sql(" SELECT *  FROM JOBS WHERE id IN(#{params[:keyword]}) ORDER BY #{sort_column} #{sort_direction}")
      @jobs = @jobs.paginate(:per_page => 20, :page => params[:page])
      puts "(((((((((((((((((((((((((((((#{@jobs})))))))))))))))))))))))))))))))))))))))"
      #@jobs = Job.search(params[:keyword].gsub(' ', '').strip).order(sort_column + " " + sort_direction)
      #  .paginate(:per_page => 20, :page => params[:page])
      render "index" and return
    end

    puts "(((((((((((((((((((((((((((((#{params[:locale]})))))))))))))))))))))))))))))))))))))))"

=begin
    if params[:locale]=="tr"
      I18n.locale = :tr
    end
    if params[:locale]=="en"
      I18n.locale = :en
    end
=end

      respond_to do |format|
        #format.html {redirect_to @jobs_path}     # burda sanirim index action'i invoke et DEGIL de
        # index action'in view template'i olan views/index.html.erb yi render et demek oluyor
        format.js
        format.json { render json: @jobs}

    end
  end

  def search_autocomplete
    #puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#{params[:keyword].gsub('+', '').strip}$$$$$$$$$$$$$$$$$$"
    #stripped = params[:keyword].gsub('+', '').strip
    #puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#{stripped}$$$$$$$$$$$$$$$$$$"
    keyword = params[:q]
    h= Array.new
    if (keyword.length > 1)
      @jobs = Job.search(keyword)
      @jobs.each do |job|
      @jobs = h << ({:id => job.id, :name => job.body.truncate(40, :separator => ' '), :location => job.location})
      end
       puts @jobs
      #@jobs = @jobs.map{|p| [p.title, p.body, p.location]}.flatten.reject(&:nil?).reject(&:blank?)
      #                    .uniq.map(&:capitalize).sort.to_json


            #.sort_by{|p| p.length}

      #@jobs = @jobs..map{|p| p.strip}
      #@jobs = ["Ankara", "Erzurum"]

      #@jobs = [{:id => "856", :name => "House"}, {:id =>"1035", :name => "Desperate Housewives"}]


      respond_to do |format|
        #format.html {render :action => 'index'}
        format.js
        format.json { render json: @jobs}  #autocomplete icin format.json { render json: @jobs} gerekiyor
      end
    end
  end

  # GET /jobs
  # GET /jobs.json
  def index
=begin
    if sort_column == "category_id" && params[:locale] == :en
      @jobs = Job.cat_by_name.paginate(:per_page => 1, :page => params[:page])
    elsif sort_column == "category_id" && params[:locale] == :tr
      @jobs = Job.cat_by_isim.paginate(:per_page => 1, :page => params[:page])
    else
      @jobs = Job.order(sort_column + " " + sort_direction).paginate(:per_page => 1, :page => params[:page])
    end
=end
    @title = t('general.main_list')

=begin
    if params[:locale]=="tr"
      loc = "tr"
    end
    if params[:locale]=="en"
      loc = "en"
    end
=end

    sorting # defined in the application controller

    respond_to do |format|
      format.html # index.html.erb
      #format.js
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    session[:time_now] = Time.now

    @job = Job.find(params[:id])
    if (Category.where("id = ?", @job.category_id).first.nil? ||
        Category.where("id = ?", @job.category_id).map{|p| p.isim} == ["Diğer"] ||
        Category.where("id = ?", @job.category_id).map{|p| p.isim} == ["Other"])
      @category = t('general.category_is_not_specified')
    elsif I18n.locale == :en
      @category = Category.where("id= ?", @job.category_id).first.name
    elsif I18n.locale == :tr
      @category = Category.where("id= ?", @job.category_id).first.isim
    end

    if request.xhr?
      render 'show_ajax', :layout => false
      #respond_to do |format|
      #  format.js
      #end

    else

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @job }
      end
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    session[:time_now] = Time.now

    2.times do
      @job.references.build
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = current_user.jobs.find(params[:id])
    @references = @job.references.all
    if @references.count == 0
      2.times do
        @job.references.build
      end
    end
    if @references.count == 1
      1.times do
        @job.references.build
      end
    end
  end

  # POST /jobs
  # POST /jobs.json
  def create
    if current_user.nil?
       redirect_to login_path and return false
    end

    @job = current_user.jobs.new(params[:job])


    @time_too_fast = ''

    #time_later # defined in application controller
    hidden_field  # defined in application controller

    respond_to do |format|
      if !@job.valid?
           @hidden = nil
           @time_too_fast = nil
           format.html do
        2.times do
          @job.references.build
          end

          render action: "new"
        end

        format.json { render json: @job.errors, status: :unprocessable_entity }
      end

      #puts @job.valid?
      #p @hidden

      if ((@hidden.blank? || @hidden.nil?) && @time_too_fast.blank?) && @job.save
        #p @job
        flash[:notice] = t('jobs_controller.create.success')
        format.html { redirect_to @job}
        format.json { render json: @job, status: :created, location: @job }
      else

        format.html do
          2.times do
            @job.references.build
            end

          render action: "new"
        end

        format.json { render json: @job.errors, status: :unprocessable_entity }

      end
    end
  end


  # PUT /jobs/1
  # PUT /jobs/1.json

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_captcha.html.erb
<div class="field">
  <%= label_tag :captcha_answer, t('general.captcha'), :class => "captcha" %>:<br />
  <%= label_tag :captcha_answer, '', :class => "notify_friend_captcha_question" %>
  <br />
  <%= text_field_tag :captcha_answer, '', :class => "notify_friend_captcha_answer" %>
</div>

app/views/jobs/_job.html.erb
<%= div_for job do %>


    <h2><%= t('jobs.job_partial.h3') %></h2>


    <br />
    <b><%= label_tag t('jobs.index.table.title') %></b>:&nbsp;<%= job.title %>
    <br />
    <b><%= label_tag t('jobs.index.table.body') %></b>:&nbsp;<%= simple_format job.body, :class => 'konu' %>
    <br />
    <b><%= label_tag t('jobs.index.table.location') %></b>:&nbsp;<%= job.location %>
    <br />
    <b><%= label_tag t('jobs.index.table.category') %></b>:&nbsp;<%= @category %>
    <br />
    <b><%= label_tag t('jobs.index.table.created_at') %></b>:&nbsp;<%= time_ago_in_words(job.created_at) %>
    <%= t('general.time_ago_in_words') %>
    <br />

    <span class='actions'>
      <% if job.owned_by? current_user %>
        <span class='actions'>
          <%= link_to t('general.edit'), edit_job_path(job) %>
          &nbsp;
          <%= link_to t('general.delete'), job, :confirm => t('general.sure'), :method => :delete %>
        </span>
      <% end %>
    </span>

    <br /><br />
    <% if job.references.blank? %>
        <%= t('general.reference_not_given') %>
    <% else  %>
        <%= link_to t('jobs.job_partial.link_to.read_reference'), '#', {:class => "link_references"} %>

        <div class="references">
          <br />
          <% for reference in job.references  %>
              <li><b><%= t('general.name') %>:</b> <%=reference.name  %></li>
              <li><b><%= t('general.last_name') %>:</b> <%=reference.lastname  %></li>
              <li><b><%= t('general.phone') %>:</b> <%=reference.phone  %></li>
              <li><b><%= t('general.cell') %>:</b> <%=reference.cell  %></li>
              <li><b><%= t('general.email') %>:</b> <%=reference.email  %></li>
              <br />
          <% end %>
        </div>
    <% end %>

    <span class='actions'>
      <% if job.owned_by? current_user %>
        <span class='actions'>
         <br />   <%= link_to t('general.edit'), edit_job_path(job)%>
        </span>
      <% end %>
    </span>
    <br/><br/>
<% end %>

app/views/jobs/_notify_friend.html.erb
<%= form_tag(notify_friend_job_path(@job), :id => 'notify_friend_form',:style => 'display:none') do %>
    <div class="field_notify_friend">
      <%= label_tag :name, t('general.your_name') %>:<br />
      <%= text_field_tag :name, '', :class => "notify_friend_name" %>
    </div>
    <div class="field_notify_friend">
      <%= label_tag :email, t('general.friends_email_address') %>:<br />
      <%= text_field_tag :email, '', :class => "notify_friend_email" %>
    </div>
    <br />
    <%= hidden_field_tag(:hidden, '', :class => "hidden_field_tag") %>
    <div class="action_notify_friend">
      <%= submit_tag t('general.send'), :class => "notify_friend_submit" %> &nbsp; <%= t('general.or') %> &nbsp;
      <%= link_to t('general.link_to.cancel'), '#', :onclick => "$('#notify_friend_form').slideUp()" %>
    </div>
<% end %>

app/views/jobs/_search.html.erb
<%= form_tag(search_by_cat_id_path, :method => :get , :class => "search_by_category") do %>
    <% if I18n.locale == :en  %>
        <%= select("job", "category_id", Category.order(:name).collect {|p| [ p.name, p.id ] },
                   {:include_blank => t('general.none') }, {:id => "select_box"}) %>

        <!-- Yukarinin asagidakiden farki yukarda :remote => true yok ajax a gerek yok-->
        <!-- select("job", "category_id", Category.order(:name).collect {|p| [ p.name, p.id ] },
                           {:include_blank => t('general.none'), :remote=>true }, {:id => "select_box"}) -->

        <!-- options_from_collection_for_select(Category.order(:name).collect {|p| [ p.name, p.id ] }, "category_id",0) -->
        <%= hidden_field_tag :direction, params[:direction] %>
        <%= hidden_field_tag :sort, params[:sort] %>
    <% elsif I18n.locale == :tr %>
        <%= select("job", "category_id", Category.order(:isim).collect {|p| [ p.isim, p.id ] },
                   {:include_blank => t('general.none') },
                   {:id => "select_box"}) %>
        <!-- select>
        < options_from_collection_for_select(Category.order(:id), "id", "isim" ,0) >
        </select -->
          <!-- For hidden_field_tag  "You have to pass first parameter as name, and second as value"

             hidden_field_tag("page", "1", {:id => "page_no"})
             hidden_field_tag :param_name, 'param_value', {:id => 'ashish_id', :name => 'another_name'}

             http://stackoverflow.com/questions/5295432/rails-how-to-assign-name-and-id-to-hidden-field-tag
        -->
        <%= hidden_field_tag :direction, params[:direction],
                                     {:id => "direction_search_by_category"} %>
        <%= hidden_field_tag :sort, params[:sort],
                                     {:id => "sort_search_by_category"} %>
        <%= hidden_field_tag :page, params[:page] %>
    <% end  %>
        <%= submit_tag t('general.search'), :class => "search_by_category_submit" %>

 <% end %>



<%= form_tag(search_jobs_path, :method => :get , :id => "search_form") do %>

      <%= hidden_field_tag :direction, params[:direction] %>
      <%= hidden_field_tag :sort, params[:sort] %>
      <%= hidden_field_tag :keyword, params[:keyword] %>


      <%= submit_tag t('general.search'), :id => "search_form_submit" %>
      <%= text_field_tag :keyword, params[:keyword], :id => "search_form_text_field" %>
<% end %>


app/views/jobs/_tabler.html.erb

 <table class="stripeMe">

  <!-- t('general.sort_by') -->
  <% if @jobs.blank?  %>

      <%= t('jobs.index.table.category') %>
      <%= t('jobs.index.table.title') %>
      <%= t('jobs.index.table.location') %>
      <%= t('jobs.index.table.body') %>
      <%= t('jobs.index.table.created_at') %>



  <% else  %>

      <!--sortable methoda gonderilen :class gereksiz ama sonra lazim olabilir diye silmiyorum.-->
      <!--sortable application_helper'da defined-->
      <!-- asagida sortable function call'dan sonra gelen parantez son derece onemli; o parantez
           olmazsa kod I18n'nin t methodunu invoke etmiyor column basliklari sirf ingilizce output oluyor. -->


      <tr class="sort_by_links_tr">
          <th id='remove_category_anchor' class='kategori'><%= sortable('category_id', t('jobs.index.table.category'), :class=>"sort_by_links") %>
          </th>

          <th class="for_after_category_removed title"><%= sortable('title', t('jobs.index.table.title'), :class=>"sort_by_links") %>
          </th>

          <th class="for_after_category_removed location"><%= sortable('location', t('jobs.index.table.location'), :class=>"sort_by_links" ) %>
          </th>

          <th class="for_after_category_removed job_body"><%= sortable('body', t('jobs.index.table.body'), :class=>"sort_by_links") %>
          </th>

          <th class="for_after_category_removed date"><%= sortable('created_at', t('jobs.index.table.created_at'), :class=>"sort_by_links") %>
          </th>

          <th>&nbsp;</th>

          <th>&nbsp;</th>

          <th>&nbsp;</th>

      </tr>
  <% end  %>

  <% if !@jobs.blank? %>
      <% @jobs.each do |job| %>
          <tr class="row">
          <td>
          <% if !job.category.nil? %>
              <% if I18n.locale == :en %>
                  <%= job.category.name %>
              <% elsif I18n.locale == :tr %>
                  <%= job.category.isim %>
              <% end %>
          <% else %>
              ---
          <% end %>
          </td>

          <td class="title"><%= truncate(job.title, :length => 10, :omission => t('general.continued')) %></td>
          <td><%= truncate(job.location, :length => 10, :omission => t('general.continued')) %></td>
          <td class="td_for_tooltip"><input type="hidden" value="<%= url_for job %>" class="input_field_for_tooltip" >
            <%= truncate(job.body, :length => 40, :separator => ' ', :omission => t('general.continued') )%></td>
          <td><%= time_ago_in_words(job.created_at) %> <%= t('general.time_ago_in_words') %></td>

          <td>
          <%= link_to t('general.link_to.show'), job, {:title => "", :class => "show"} %>
          </td>

          <%# p "**********************************************" + current_user.is_admin?.to_s %>
          <% if !current_user.nil? %>
            <% if (job.owned_by?(current_user) || current_user.is_admin?) %>
                <td class="member_specific_edit"><%= link_to t('general.edit'), edit_job_path(job), {:class => "visited"} %></td>
                <td class="member_specific_delete">
                <%= link_to t('general.delete'), job, confirm: t('general.sure'), method: :delete, :class => "visited" %>
                </td>
            <% else %>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            <% end %>
          <% else %>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
          <% end %>
            </tr>
      <% end %>
  <% end %>

   </table>


<br />
<!-- will_paginate(@jobs, :params => { :controller => "jobs", :action => "search_by_category" })-->
<%= will_paginate_with_i18n(@jobs, :class => 'pagination for_all_listing') %>
<!-- will_paginate_with_i18n(@jobs, :class => 'pagination for_select_box_listing') -->
<!-- will_paginate_with_i18n(@jobs, :class => 'pagination for_autocomplete_listing') -->

<br />

app/views/jobs/edit.html.erb
<h1><%= t('general.editing_job') %></h1>

<%= render 'form' %>

<div class="field1">
<br />
<%= link_to t('general.job_page'), @job %> |
<%= link_to t('general.link_to.root_path'), jobs_path %>
<br /><br />
<% if logged_in? and current_user.jobs.count > 0 %>
    <%= link_to t("general.listed_jobs"), user_jobs_path %>
<% end  %>



<br /><br /><br />
</div>

app/views/jobs/index.html.erb
 <div id = "for_ajax">
  <br />
  <div class="main_title"><%= link_to 'isgetir.com', root_path %></div>

  <br /><br />
  <div class = 'index'>


    <%= image_tag "chef.jpg", :size => "75x75", :alt => "Resim" %>
    <%= image_tag "girl.jpg", :size => "75x75", :alt => "Resim" %>
    <%= image_tag "graduate.jpg", :size => "75x75", :alt => "Resim" %>
    <%= image_tag "man.jpg", :size => "75x75", :alt => "Resim" %>
    <%= image_tag "group.jpg", :size => "75x75", :alt => "Resim" %>

  </div>

  <%= render "users/header" %>

  <div id = "listing_jobs_line">
    <span class="listing_jobs"><%= t('general.h1.listing_jobs') %></span>
    <% if !logged_in? %>
      <%= link_to t("general.listed_jobs"), login_for_user_jobs_path(:login_for_user_jobs => 1), {:class => "my_jobs"} %>
    <% else %>
      <%= link_to t("general.listed_jobs"), user_jobs_path, {:class => "my_jobs"} %>
    <% end %>
  </div>


  <%= render 'jobs/search' %>
  <div class="spinner">
    <%= link_to t('general.main_list'), root_path, :id => 'main_list_link' %>
  </div>
  <!-- if I18n.locale == :en  %> burdan jobs/search'e kaldirildi
   < select("job", "category_id", Category.order(:name).collect {|p| [ p.name, p.id ] },
              {:include_blank => t('general.none'), :remote=>true }, {:id => "select_box"}) %>
< elsif I18n.locale == :tr %>
   < select("job", "category_id", Category.order(:isim).collect {|p| [ p.isim, p.id ] },
              {:include_blank => t('general.none'), :remote=>true }, {:id => "select_box"} ) %>
< end  -->

  <div id="main_table"><%= render 'jobs/tabler' %></div>

 </div>

 <div class="for_spinner" style="display: none;"></div>

 <br /><br /><br /><br />
  <%= debug(params) if Rails.env.development? %>

app/views/jobs/new.html.erb
<h2 class='new_job_h2'><%= t('general.h2.new_job') %></h2>

<%= render 'form' %>

<div class='field1'>

<br />

<%= link_to t('general.link_to.root_path'), jobs_path %>


<br /><br /><br />

</div>

app/views/jobs/show.html.erb
<div class='vr'><%= image_tag 'column.png', :size => '100x500' %></div>



<div class = "captcha_alternatives">
<%= @time_too_fast.nil? ? '' : @time_too_fast%>
<%= @hidden.nil? ? '' : @hidden %>
</div>




<!--<div id='notice'>
 < render :partial => 'layouts/flash' , :locals => { :flash => flash } %>
</div>-->

<%= render @job %>

<%= link_to t('jobs.show.link_to.email_a_friend'), '#',
        :id => "show_link_to_email_friend" %>
<br /> <br />

<%= render 'jobs/notify_friend' %>
<br />


<h2>
  <%= t('general.comments') %>
</h2>



<div id="comments">
    <%= render @job.comments %>
</div>

<br />

<!-- asagida :format => :js i cikarsanda program aynen calisiyor -->
<%= link_to t('jobs.show.link_to.new_comment'), new_job_comment_path(@job, :format => :js),
:remote => true, :id => 'new_comment_link' %>

<br /><br />


<%= hidden_field_tag(:hidden, '', :class => "hidden_field_tag") %>


<% if logged_in? and current_user.jobs.count > 0 %>
    <%= link_to t("general.listed_jobs"), user_jobs_path %>
<% end  %>

<br /><br />
<%= link_to t('jobs.show.link_to.jobs_list'), jobs_path %>



<br /><br /><br />

app/views/jobs/show_ajax.html.erb
    <!-- image_tag "men_at_work_image.jpeg",
                  :size => "25x25",
                  :alt => "Picture Men At Work",
                  :class=>"matwork" -->

    <%= @job.body %>

<!-- p class="show_ajax"
     word_wrap(@job.body, :line_width => 250)
     word_wrap calismiyor
     p
     puts @job.body.inspect -->