config/routes.rb
Isgetir::Application.routes.draw do

  root :to => 'jobs#index'

  match ':locale/jobs/search' => 'jobs#search', :as => "search"
  match 'jobs/search_autocomplete' => 'jobs#search_autocomplete'
  match ':locale/search_by_cat_id' => 'jobs#search_by_cat_id', :as => 'search_by_cat_id' # according to
  match ":locale/jobs/user_jobs" => "jobs#user_jobs", :as => "user_jobs"

  match 'comment_destroy_path' => "comments#destroy"

  scope "/:locale" do
    resources :jobs do

      member do
        post :notify_friend
      end
      collection do
        get :search_autocomplete
        get :search
        get :ajaxing
        get :search_by_cat_id
      end
      resources :comments
    end
  end

  match 'users/admin_update_user_interface' => 'users#admin_update_user_interface', :as => 'admin_update_user_interface'

=begin

  match 'users/admin_updated_user' => 'users#admin_updated_user', :as => 'admin_updated_user'

  match 'users/admin_manage' => 'users#admin_manage', :as => 'admin_manage'

  match 'users/admin' => 'users#admin', :as => 'user_admin'

  match 'users/admin_edit_user' => "users#admin_edit_user", :as => 'admin_edit_user'

  match 'users/admin_change_password' => 'users#admin_change_password', :as => 'admin_change_password'

  resources :users
=end

  match ":locale/admin_manage/:manage" => "users#admin_manage", :as => "admin_manage_users"

  scope "/:locale" do
    resources :users do
      collection do
        put :admin_updated_user
        get :admin_update_user_interface
        get :admin
        get :admin_edit_user
        put :admin_change_password
      end
    end
  end

  match 'users/destroy' => "users#destroy"

  resource :session, :only => [:new, :create, :destroy] # , :only => [:new, :create, :destroy] added after reading rails by example

  resources :password_resets

  match ":locale/login_for_user_jobs/:login_for_user_jobs" => "sessions#new", :as =>"login_for_user_jobs"

  match '/login' => "sessions#new", :as => "login" # according to
  match '/logout' => "sessions#destroy", :as => "logout" # according to

end

app/models/user.rb
require "digest"

class User < ActiveRecord::Base

  attr_accessible :email, :password, :password_confirmation
  attr_accessor :password, :password_confirmation

  before_create { generate_token(:auth_token) }

  has_one :profile
  has_many :jobs, :order => 'created_at DESC, title ASC',
           :dependent => :nullify
  #has_many :replies, :through => :skills, :source => :comments


  validates :email, :uniqueness => {:case_sensitive => false},
            :length => { :within => 5..50 },
            :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }

  validates :password, :confirmation => true,
            :length => { :within => 5..20 },
            :presence => true,
            :if => :password_required?

   validates :password_confirmation,
            :length => { :within => 5..20 },
            :presence => true,
            :if => :password_required?

  #before_save :encrypt_new_password

  before_save :encrypt_password  # added

  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end
  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    Notifier.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  protected
  # def encrypt_new_password
  def encrypt_password
    #return if password.blank?
    self.salt = make_salt if new_record? # added line
    self.hashed_password = encrypt(password)
  end

  # encrypt method added
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def password_required?
    hashed_password.blank? || password.present?
  end

  #def encrypt(string)
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/users_controller.rb
require 'will_paginate/array'

class UsersController < ApplicationController
  #force_ssl
  before_filter :authenticate, :only => [:index, :edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => [:destroy]

  def new
    session[:time_now] = Time.now
    @user = User.new
  end
  def create

    if params[:category_id] != "" && params[:category_id] != ""
      path = search_by_cat_id_path(:locale => 'tr',:category_id => params[:category_id], :sort => params[:sort], :direction => params[:direction])
      puts "**************************************************************************************search_by_cat_id_path"
    elsif params[:keyword] !=""
      path = search_path(:locale => 'tr',:category_id => params[:category_id], :sort => params[:sort], :direction => params[:direction],:keyword => params[:keyword], :page => params[:page])
      puts "**************************************************************************************search_path"
    else
      path = jobs_path
      puts "**************************************************************************************jobs_path"
    end

  if !Rails.env.test?
   @time_too_fast = ''

    time_later # defined in application controller
    hidden_field  # defined in application controller

    if !@hidden.blank?
      flash[:notice] = t('general.hidden_text_field_change')
      @user = User.new
      render :action => 'new' and return
    end

    if !@time_too_fast.blank?
      flash[:notice] = t('general.too_fast')
      @user = User.new
      render :action => 'new' and return
    end
  end

    @user = User.new(params[:user])

    if @user.save
      if is_admin?
        flash[:notice] = t('users_controller.create.success')
        redirect_to new_user_path and return false end
      session[:user_id] = @user.auth_token
      redirect_to path, :notice => t('users_controller.create.success')
    else
      render :action => 'new'
    end
  end

  def edit
    #@user = current_user  # correct_user takes care of this line
  end

  def admin_edit_user
     if is_admin?
      render 'admin_edit_user'
    end
  end

  def admin_change_password

    user = {:id => params[:User][:id], :password=>params[:password],
            :password_confirmation=>params[:password_confirmation]}
    @user = User.find_by_id(params[:User][:id])
    puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                        #{@user}                                  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"

    if @user.nil?
      flash[:notice] = t('general.choose')
      redirect_to admin_edit_user_users_path and return false
    end

    if params[:password].blank?
      @user.errors.add(:password, t('general.password_cannot_be_blank_admin_pages'))
      render 'admin_edit_user' and return false
    end

    if params[:password] != params[:password_confirmation]
      @user.errors.add(:password, t('activerecord.errors.models.user.attributes.password.confirmation'))
      render 'admin_edit_user'
    elsif @user.update_attributes(user)
      redirect_to admin_users_path, :notice => t('users_controller.update.success')
    else
      render 'admin_edit_user'
    end

  end

  def update
    #@user = current_user  # correct_user takes care of this line
    if params[:user][:password].blank?
      @user.errors.add('', t('general.password_cannot_be_blank'))
      render :action => 'edit'
    elsif @user.update_attributes(params[:user])
      redirect_to jobs_path, :notice => t('users_controller.update.success')
    else
      render :action => 'edit'
    end
  end

  def admin_update_user_interface
    #puts "_______________________________________________________ #{params}"
    @user = User.find_by_id(params[:user])
    #p @user
    @jobs = @user.jobs
    flash[:notice]=""
    flash[:alert]=""
  end

  def admin_updated_user

    #puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ #{params}"

    @user = User.find_by_id(params[:user_id])
    @job = @user.jobs.find_by_id(params[:job_id])



    respond_to do |format|
      if @job.update_attributes(params[:job])
        flash[:notice] = t('jobs_controller.update.success')
        format.html
        format.json { head :ok }
      else
        format.html { render action: 'admin_update_user_interface' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end


  def index

    if self.is_admin?
      @user = User.paginate(:page => params[:page])
    else
      redirect_to root_path
    end

  end

  def destroy
     #@admin_type1 = params[:id]
     #@admin_type2 = params[:manage]
      @destroy ='delete'

    if !current_user.nil? && current_user.is_admin?
      #p params
      if !params[:users].nil?
        @user = User.find(params[:users])
        User.destroy(@user)
      end
      if (params[:page].blank?)
        @user = User.paginate(:page => 1)
        #@page = 1
      else
        #@page = params[:page]
        @user = User.paginate(:page => params[:page])
        puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$       #{@user}            $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
        #render :js => "alert('Hello Rails');"
      end

      #redirect_to(admin_manage_users_path, :admin => "delete", :page => @page) and return false
      #puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ #{@user}"

        respond_to do |format|
          #format.html
          format.js  # burda destroy.js.erb invoke edilsin istiyorum
          format.html
        end
      #end
     else
      redirect_to root_path
    end
  end

  def show

  if (params[:page].nil?)
    @user = User.paginate(:page => 1)
  else
    @user = User.paginate(:page => params[:page])
  end

  render 'admin_manage'

  end

  def admin
  end

  def admin_manage
    puts "_______________________________________________________ #{params}"
    if self.is_admin?
      @user = User.paginate(:page => params[:page])
    else
      redirect_to root_path
    end

     @admin_type1 = params[:id]
     @admin_type2 = params[:manage]

    #respond_to do |format|
    #  format.html {
        render 'admin_manage'
      #}
      #format.js
    #end

  end

  private
  def correct_user
    @user = User.find_by_id(params[:id])   # find_by_id returns nil if user with the id not found v.s. find which returns an exception
    redirect_to(root_path) unless !@user.nil? && current_user == @user
  end

  def admin_user
    if !current_user.nil?
    redirect_to(root_path) unless current_user.is_admin?
    else
      false
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, :builder => TidyFormBuilder ) do |f| %>
    <% if @user.errors.any? %>
        <br />
        <div class="errorExplanation">
          <h3>
            <%= pluralize(@user.errors.count,
                            t("general.pluralize.error"), t("general.pluralize.error")) %>
            <% if @user.errors.count > 1 %>
                <%= t('general.error_explanations')%>:
            <% else %>
                <%= t('general.error_explanation')%>:
            <% end %>
          </h3>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><b><%= msg %></b></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <!-- f.label t('general.email') %>:<br />  -->
      <%= f.text_field :email, {:i18n => t('general.email'),
                                :required => true, :tooltip => t('general.class_required') } %>
    </div>
    <div class="field">
      <!-- f.label t('general.password') %>:<br />  -->
      <%= f.password_field :password, {:i18n => t('general.password'),
                                :required => true, :tooltip => t('general.class_required') } %>
    </div>
    <div class="field">
        <!-- t('general.password_confirmation') %>:<br /> -->
      <%= f.password_field :password_confirmation, {:i18n => t('general.password_confirmation'),
                                :required => true, :tooltip => t('general.class_required') } %>
    </div>
    <br />



      <%= hidden_field_tag(:hidden, '', :class => "hidden_field_tag") %>

      <%= hidden_field_tag :category_id, params[:category_id] %>
      <%= hidden_field_tag :direction, params[:direction] %>
      <%= hidden_field_tag :sort, params[:sort] %>
      <%= hidden_field_tag :keyword, params[:keyword] %>
      <%= hidden_field_tag :page, params[:page] %>

    <div class="submit_actions">
      <br /><br />
      <%= f.submit t('general.submit') %>
      &nbsp;<%= t('general.or') %> &nbsp;
      <%= link_to t('general.link_to.back'), "#", :class => "geri" %>
    </div>
      <br />
      <%= link_to t('general.main_list'),root_path, { :class=>"root"} %>
       <% if logged_in? && current_user.is_admin? %>
        <br />
        <br />
      <%= link_to t('general.admin'), admin_users_path %>
      <% end %>
<% end %>





app/views/users/_header.html.erb
<div id="header">

  <%= language_selector %>
  <!-- image_tag "United_Kingdom.png" -->

  <br />
  <div class="menu">
    <% if !params[:job].nil? %>
      <%  path = {:locale => 'tr',:category_id => params[:job][:category_id], :sort => params[:sort], :direction => params[:direction],:keyword => params[:keyword], :page => params[:page]} %>
    <% else %>
        <%  path = {:locale => 'tr',:category_id => params[:category_id], :sort => params[:sort], :direction => params[:direction],:keyword => params[:keyword], :page => params[:page]} %>
    <% end %>

    <% if logged_in? %>
        <%= link_to t("general.menu.new_job"), new_job_path %> |
        <%= link_to t("general.menu.edit_password"), edit_user_path(current_user) %> |
        <%= link_to t("general.menu.logout"), logout_path(path) %>
    <% else %>
        <%= link_to t("general.menu.create_user"), new_user_path(path) %> |
        <%= link_to t("general.menu.login"), login_path(path) %>

     <% end %>
    <% if logged_in? && is_admin? %>
      | <%= link_to t('general.admin'), admin_users_path %>
    <% end %>
  </div>
</div>
  <br /><br />

  <!-- link_to t('general.link_to.root_path'), root_path, :id => 'link_to_below_search' -->
  <br />




app/views/users/_user.html.erb
<% unless current_user.email == user.email %>
  <ul>
    <li>
      <%= user.email %>
    </li>
  </ul>
<% end %>

app/views/users/admin.html.erb
<div class='admin_page'>
<%= link_to t('admin.show_users'), users_path %>
<br />
<%= link_to t('admin.edit_user_job'), admin_manage_users_path(:manage => "manage") %>
<br />
<%= link_to t("admin.delete_users"), admin_manage_users_path(:manage => "delete") %>
<br />
<%= link_to t("admin.add_user"), new_user_path %>
<br />
<%= link_to t("admin.change_password"), admin_edit_user_users_path %>
<br />
<br />

  <%= link_to t('general.main_list'),root_path, { :class=>"root"} %>
</div>

app/views/users/admin_edit_user.html.erb
<div class="change_password">

  <% if !@user.nil? %>

     <% if @user.errors.any? %>
          <!-- puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! #{@user.errors.to_s}" -->
        <br />
        <div class="errorExplanation">
          <h3>
            <%= pluralize(@user.errors.count,
                            t("general.pluralize.error"), t("general.pluralize.error")) %>
            <% if @user.errors.count > 1 %>
                <%= t('general.error_explanations')%>:
            <% else %>
                <%= t('general.error_explanation')%>:
            <% end %>
          </h3>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><b><%= msg %></b></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>

  <%= form_tag({:controller => 'users', :action => 'admin_change_password'}, :autocomplete=>"off" , :method => :put) do %>

    <%= collection_select(:User, :id, User.order(:email), :id, :email,
                             {:prompt => false}, {:id => 'collection_select',:size => 10}) %>

    <!-- select("user", "id", User.order(:email).collect {|p| [ p.email, p.id ] },
              {:include_blank => t('general.none')}, {:id => "select_box"}) -->

    <br /><br />
    <div class="password_field">
      <b><%= label_tag :password, t('general.password') %></b> <br />
      <%= password_field_tag :password %>
    </div>
    <br />
    <div class="password_field">
      <b><%= label_tag :password_confirmation, t('general.password_confirmation') %></b> <br />
      <%= password_field_tag :password_confirmation %>
    </div>
  <br />
  <%= submit_tag t('general.change_password') %>
      <% end  %>
      <br /> <br />
  <%= link_to t('general.main_list'),root_path, { :class=>"root"} %>
</div>

<br />
<br />
<%= link_to t('general.admin'), admin_users_path %>

app/views/users/admin_manage.html.erb
<div class="users">

<% if params[:destroy] =='delete' || params[:manage]=="delete" || @destroy == "delete" %>

  <%= form_tag({:controller => 'users', :action => 'destroy'}, :method => :delete, :remote => true, :class => 'delete_form_tag') do %>
    <% @user.each do |user| %>
        <% unless current_user.email == user.email %>
            <ul>
              <li>
                <%= user.email %>
                <%= check_box_tag "users[]", user.id, false %>
              </li>
            </ul>
        <% end %>
    <% end  %>
    <br />
    <%= submit_tag t('general.remove'), :class => "submit_button_for_users_destroy"%>
    <%= hidden_field_tag :page, params[:page] %>
    <%= hidden_field_tag :destroy, params[:manage] %>
    <br /> <br />
  <% end %>

<% else %>

  <% @user.each do |user| %>
    <ul>
      <li>
        <%= link_to user.email, admin_update_user_interface_users_path(:user => user.id),
                                            {:class => "user_email_link_in_admin_manage"}%>
      </li>
    </ul>
  <% end %>
<% end %>

  <br /> <br />
  <%= will_paginate_with_i18n(@user) %>
  <br /> <br /><br /> <br /><br /> <br />
  <%= link_to t('general.main_list'),root_path, { :class=>"root"} %>
  <br />
  <br />
  <br />
  <br />
  <%= link_to t('general.link_to.admin'), admin_users_path %>
</div>

<div id="dialog-confirm" title="<%= t('general.delete') %>" style="display: none">
  <p>
      <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0">
      </span>
    <%= t('general.permanent') %>
  </p>
</div>

app/views/users/admin_manage.js.erb
$("#main").html("<%= escape_javascript(render(:file => "users/admin_update")) %>");
var admin_type = "<%= @admin_type %>"

var batin = $("input:submit");
batin.button();

$(".submit_button_for_users_destroy").prop('value', "Edit")

batin.on ('click',  function() {
    batin.attr("disabled", true);
});

var params = $('.delete_form_tag').serialize();

$('.submit_button_for_users_destroy').live('click', function() {
     $.ajax({
            url: '/users/admin_update_user',
            type: 'POST',
            data: {manage:'manage'},
            dataType: "script"
//          success: function(result) {}
        });
    return false
})


var locale = $("div.set_locale").text();

if(locale=="tr")
   $(".favicon").attr("href", "/assets/is.ico");
if(locale=="en")
   $(".favicon").attr("href", "/assets/job.ico");

app/views/users/admin_update_user_interface.html.erb
<b><%= @user.email %></b>

<br />
<br />

<% job_count = @jobs.count %>


<% @jobs.each do |job| %>
<div class = "update_job_form">

<%= form_for job, :url => {:controller => :users, :action => :admin_updated_user}, :builder => TidyFormBuilder do |f| %>
  <%= hidden_field_tag :user_id, @user.id %>
  <%= hidden_field_tag :job_id, job.id %>
  <% if job.errors.any? %>
    <div class="errorExplanation">
      <h3>
        <%= pluralize(job.errors.count, t("general.pluralize.error"),
                                        t("general.pluralize.error")) %>!
        <br />
        <% if job.errors.count > 1 %>
            <%= t('general.error_explanations')%>:
        <% else %>
            <%= t('general.error_explanation')%>:
        <% end %>
      </h3>
      <% css_class_title = job.errors.include?(:title) ? "highlight_error_class_title" : "no_problem_class" %>
      <% css_class_body = job.errors.include?(:body) ? "highlight_error_class_body" : "no_problem_class" %>
        <ul>
           <% job.errors.full_messages.each do |msg| %>
             <li>
               <b>
                 <%= msg %>
               </b>
             </li>
          <%end %>
        </ul>
    </div>
  <% end %>

  <div class="field">
    <br />
    <b><%= t('jobs.job_partial.h3') %> #<%= job_count %></b>
    <br />
    <br />
    <!-- = f.label t('jobs.index.table.title'), :class => css_class_title %><br / -->
    <%= f.text_field :title, {:i18n => t('jobs.index.table.title'), :required => true, :tooltip => t('general.class_required'), :class => css_class_title } %>
  </div>
  <div class="field">
    <!-- f.label t('jobs.index.table.location') %><br / -->
    <%= f.text_field :location, {:i18n => t('jobs.index.table.location')}  %>
  </div>

   <div class="field">
    <br />
    <% if job.references.count == 1 %>
        <h3><%= t('general.reference') %></h3>
    <% else %>
        <h3><%= t('general.references') %></h3>
    <% end %>

    <% if job.references.blank? %>
        <%= t('general.reference_not_given') %>
    <% else  %>
        <h3><%= t('general.references') %></h3>

        <%= f.fields_for :references do |builder| %>
            <%= render 'jobs/reference', :f => builder %>
        <% end %>
    <% end %>
  </div>

  <div class="field1">
     <br /><br /><br />
     <%= f.label t('jobs.index.table.category')%><br />
      <!--select("job", "category_id", Category.all.sort.collect {|p| [ p.name, p.id ] },-->
                <!--{:include_blank => 'None'}, {:class => "select_box"}) %>-->
     <!--collection_select(:person, :city_id, City.all, :id, :name) -->
     <% if I18n.locale == :en %>

        <%= f.collection_select(:category_id, Category.order(:name), :id, :name,
                             {:prompt => t('general.other')}, {:id => 'collection_select',:size => 7}) %>
     <% elsif I18n.locale == :tr  %>
         <%= f.collection_select(:category_id, Category.order(:id), :id, :isim,
                                      {:prompt => t('general.other')}, {:id => 'collection_select',:size => 7}) %>
     <% end %>
  </div>

   <div class="field1">
     <br /><br /><br />
     <!-- f.label t('jobs.index.table.body'), :class => css_class_body %><br />  -->
     <%= f.text_area :body, {:i18n => t('jobs.index.table.body'), :required => true, :tooltip => t('general.class_required'), :class => css_class_body } %>
   </div>
<!--
  <div class="field">
    f.label l(:published_at) %><br />
    f.datetime_select l(:published_at) %>
  </div>
  <div class="field">
    f.label :created_at %><br />
     f.datetime_select :created_at %>
  </div>
-->
    <div class="field1">
        <br />
        <%= submit_tag t('general.submit'), :class => "submit_in_update_user_interface" %> <!-- &nbsp; < t('general.or') %> &nbsp;  -->
        <br />
        <br />
    </div>

    <!-- hidden field is for captcha alternative to check whether '' is changed
           by bots. Check is made in the application controller hidden_field method
    -->
    <%= hidden_field_tag(:hidden, '', :class => "hidden_field_tag") %>
    <%= hidden_field_tag :admin, params[:admin] %>

<% end %>
</div>
<% job_count = job_count -1 %>
<% end %>

<div class = "links_in_admin_update_user_interface">
   <%= link_to t('general.link_to.admin'), admin_users_path %>
   <br /><br />
   <%= link_to t('general.link_to.manage'), admin_manage_users_path(:manage =>"manage"), :class => "back_link_in_admin_update_user" %>
</div>

app/views/users/admin_updated_user.html.erb
<% @job = Array(@job) %>

<% @job.each  do |job| %>

<%= hidden_field_tag :user, @user.id, :class => "user_in_admin_updated_user" %>

<%= div_for job do %>


    <h2><%= t('jobs.job_partial.h3') %></h2>


    <br />
    <b><%= label_tag t('jobs.index.table.title') %></b>:&nbsp;<%= job.title %>
    <br />
    <b><%= label_tag t('jobs.index.table.body') %></b>:&nbsp;<%= simple_format job.body, :class => 'konu' %>
    <br />
    <b><%= label_tag t('jobs.index.table.location') %></b>:&nbsp;<%= job.location %>
    <br />
    <b><%= label_tag t('jobs.index.table.category') %></b>:&nbsp;<%= @category %>
    <br />
    <b><%= label_tag t('jobs.index.table.created_at') %></b>:&nbsp;<%= time_ago_in_words(job.created_at) %>
    <%= t('general.time_ago_in_words') %>
    <br />

    <span class='actions'>
      <% if job.owned_by? current_user %>
        <span class='actions'>
          <%= link_to t('general.edit'), edit_job_path(job) %>
          &nbsp;
          <%= link_to t('general.delete'), job, :confirm => t('general.sure'), :method => :delete %>
        </span>
      <% end %>
    </span>

    <br /><br />
    <% if job.references.blank? %>
        <%= t('general.reference_not_given') %>
    <% else  %>
        <%= link_to t('jobs.job_partial.link_to.read_reference'), '#', {:class => "link_references"} %>

        <div class="references">
          <br />
          <% for reference in job.references  %>
              <li><b><%= t('general.name') %>:</b> <%=reference.name  %></li>
              <li><b><%= t('general.last_name') %>:</b> <%=reference.lastname  %></li>
              <li><b><%= t('general.phone') %>:</b> <%=reference.phone  %></li>
              <li><b><%= t('general.cell') %>:</b> <%=reference.cell  %></li>
              <li><b><%= t('general.email') %>:</b> <%=reference.email  %></li>
              <br />
          <% end %>
        </div>
    <% end %>

<!--    <span class='actions'>
      < if job.owned_by? current_user %>
        <span class='actions'>
         <br />   < link_to t('general.edit'), edit_job_path(job)%>
        </span>
      < end %>
    </span> -->

    <br/><br/>
<% end %>

<% end %>

<%= link_to t('general.link_to.admin'), admin_users_path %> &nbsp;| &nbsp;
<%= link_to t('general.link_to.back'), '#', :class => "back_link_in_admin_updated_user_interface" %>
<br /><br />
<%= link_to t('general.link_to.manage'), admin_manage_users_path(:manage=>"manage"), :class => "back_link_in_admin_update_user" %>

app/views/users/destroy.html.erb
<div class="users">
 <%= form_tag({:controller => 'users', :action => 'destroy'}, :method => :delete, :remote => true, :class => 'delete_form_tag') do %>
    <% @user.each do |user| %>
        <% unless current_user.email == user.email %>
            <ul>
              <li>
                <%= user.email %>
                <%= check_box_tag "users[]", user.id, false %>
              </li>
            </ul>
        <% end %>
    <% end  %>
    <br />
    <%= submit_tag t('general.remove'), :class => "submit_button_for_users_destroy"%>
    <%= hidden_field_tag :page, params[:page] %>
    <%= hidden_field_tag :destroy, params[:manage] %>
    <br /> <br />
 <% end %>

   <%= will_paginate_with_i18n(@user) %>
  <br /> <br /><br /> <br /><br /> <br />
  <%= link_to t('general.main_list'),root_path, { :class=>"root"} %>
  <br />
  <br />
  <br />
  <br />
  <%= link_to t('general.link_to.admin'), admin_users_path %>
</div>

<div id="dialog-confirm" title="<%= t('general.delete') %>" style="display: none">
  <p>
      <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0">
      </span>
    <%= t('general.permanent') %>
  </p>
</div>

app/views/users/destroy.js.erb
$(".users").html("<%= escape_javascript(render(:file => "users/admin_manage", :formats => [:html])) %>");

var batin = $("input:submit");
batin.button();


batin.on ('click',  function() {
    batin.attr("disabled", true);
});

app/views/users/edit.html.erb
<div class="change_password">
<br />
<%= render 'form' %>
<br />
<%= link_to t('general.link_to.back'), jobs_path %>
</div>

app/views/users/index.html.erb
<div class="users">


  <%= render @user, :user => @user %>

<!--   < @user.each do |user| %>
      < unless current_user.email == user.email %>
          <ul>
            <li>
              < user.email %>
            </li>
          </ul>
      < end %>
  < end  %> -->

  <%= will_paginate_with_i18n(@user) %>

  <br />
  <br /> <br /><br /> <br />
  <%= link_to t('general.main_list'),root_path, { :class=>"root"} %>
</div>


<br />
<br />
<%= link_to t('general.admin'), admin_users_path %>

app/views/users/new.html.erb


<h2><%= t('general.new_user') %></h2>
<div class="menu">
  <% if !logged_in? %>
    <%= link_to t('general.login'), login_path %>
  <% end  %>
</div>
<%= render 'form' %>


<br />
<br />
<br />

 <!-- if is_admin? >
        < link_to t('general.admin'), admin_users_path >
    < end -->

<!-- if is_admin? %>
< link_to t('general.admin'), user_admin_path %>
< end -->